apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang 
  labels:
    app: golang  
  namespace: demo
spec:
  ## Set to 5 for start of lab
  replicas: 5
  selector:
    matchLabels:
      env: golang
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        env: golang 
    spec:
      containers:
      - name: golang-container 
        image: golang 
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
  labels:
    app: golang 
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: bnb-frontend-deploy
  ports:
  - port: 3000
    targetPort: 3000
