apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: demo
spec:
  ## Set to 5 for start of lab
  replicas: 5
  selector:
    matchLabels:
      env: demo
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: nginx 
  namespace: demo
spec:
  type: nodePort 
  selector:
    app: nginx
  ports:
  - port: 5000
    targetPort: 5000
